from gocept.net.configure.kvm import ensure_vms, VM
import mock
import os
import shutil
import tempfile
import unittest


def make_vm(**kw):
    result = {'name': 'test00',
              'parameters': {'id': 1000,
                             'online': False,
                             'memory': 512,
                             'cores': 1,
                             'resource_group': 'test',
                             'disk': 10,
                             'interfaces': {'srv': {'mac': 'foo'}}}}
    result['parameters'].update(kw)
    return result


class KVMConfigTest(unittest.TestCase):

    def setUp(self):
        os.environ['PUPPET_LOCATION'] = 'dev'
        self.p_directory = mock.patch('gocept.net.directory.Directory')
        self.fake_directory = self.p_directory.start()

    def tearDown(self):
        del os.environ['PUPPET_LOCATION']
        self.p_directory.stop()

    @mock.patch('gocept.net.configure.kvm.VM.ensure')
    def test_no_actions_on_empty_list(self, ensure):
        with self.assertRaises(SystemExit) as e:
            ensure_vms()
        assert e.exception.code == 0
        self.assertEquals(ensure.call_count, 0)

    @mock.patch('gocept.net.configure.kvm.VM.ensure')
    def test_listed_vms_get_ensure_called(self, ensure):
        self.fake_directory().list_virtual_machines.return_value = [
            make_vm()]
        with self.assertRaises(SystemExit) as e:
            ensure_vms()
        assert e.exception.code == 0
        self.assertEquals(ensure.call_count, 1)


class VMTest(unittest.TestCase):

    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        open(self.tmpdir+'/kvm', 'w').close()
        VM.confdfile = '{}/confd.{{name}}'.format(self.tmpdir)
        VM.initfile = '{}/init.{{name}}'.format(self.tmpdir)
        VM.runlevelfile = '{}/runlevel.default.{{name}}'.format(self.tmpdir)

        self.p_call = mock.patch('gocept.net.configure.kvm.call')
        self.call = self.p_call.start()

        self.p_subpcall = mock.patch('subprocess.check_call')
        self.subpcall = self.p_subpcall.start()

    def tearDown(self):
        shutil.rmtree(self.tmpdir)
        self.p_call.stop()
        self.p_subpcall.stop()

    def test_vm_not_running_but_should_be(self):
        vm = VM(make_vm(online=True, kvm_host='foo'), this_kvm_host='foo')
        self.assertEquals(vm.run_here, True)
        vm.ensure()
        self.assertEquals(open(vm.confdfile, 'r').read(), """\
# configure-kvm: do not edit this file directly. It will be overwritten!
VMMEM="512"
VMCORES="1"
VMRG="test"
VMDISK="10"
TAPID="1000"
VNC_PORT="1000"
MONITOR_PORT="21000"
NETWORKS="SRV"
MACSRV="foo"
""")
        self.assertEquals(os.readlink(vm.initfile), 'kvm')

        self.assertEquals(len(self.subpcall.mock_calls), 1)
        self.assertEquals(self.subpcall.mock_calls[0],
                          mock.call([vm.initfile, 'restart']))

        self.assertEquals(len(self.call.mock_calls), 1)
        self.assertEquals(
            self.call.mock_calls[0],
            mock.call('rc-update', 'add', 'kvm.test00', 'default'))

    def test_vm_running_and_should_be(self):
        vm = VM(make_vm(online=True, kvm_host='foo'), this_kvm_host='foo')
        self.assertEquals(vm.run_here, True)
        vm.is_running = lambda: True
        vm.ensure()
        self.assertEquals(open(vm.confdfile, 'r').read(), """\
# configure-kvm: do not edit this file directly. It will be overwritten!
VMMEM="512"
VMCORES="1"
VMRG="test"
VMDISK="10"
TAPID="1000"
VNC_PORT="1000"
MONITOR_PORT="21000"
NETWORKS="SRV"
MACSRV="foo"
""")
        self.assertEquals(os.readlink(vm.initfile), 'kvm')

        self.assertEquals(len(self.subpcall.mock_calls), 0)

        self.assertEquals(len(self.call.mock_calls), 1)
        self.assertEquals(
            self.call.mock_calls[0],
            mock.call('rc-update', 'add', 'kvm.test00', 'default'))

    def test_vm_running_but_should_not_be(self):
        vm = VM(make_vm(online=False, kvm_host='foo'), this_kvm_host='foo')
        self.assertEquals(vm.run_here, False)
        open(vm.runlevelfile, 'w').close()
        vm.is_running = lambda: True
        vm.ensure()
        self.assertEquals(open(vm.confdfile, 'r').read(), """\
# configure-kvm: do not edit this file directly. It will be overwritten!
VMMEM="512"
VMCORES="1"
VMRG="test"
VMDISK="10"
TAPID="1000"
VNC_PORT="1000"
MONITOR_PORT="21000"
NETWORKS="SRV"
MACSRV="foo"
""")
        self.assertEquals(os.readlink(vm.initfile), 'kvm')

        self.assertEquals(len(self.subpcall.mock_calls), 1)
        self.assertEquals(self.subpcall.mock_calls[0],
                          mock.call([vm.initfile, 'stop']))

        self.assertEquals(len(self.call.mock_calls), 1)
        self.assertEquals(
            self.call.mock_calls[0],
            mock.call('rc-update', 'del', 'kvm.test00', 'default'))

    def test_vm_stopped_and_should_be(self):
        vm = VM(make_vm(online=False, kvm_host='foo'), this_kvm_host='foo')
        self.assertEquals(vm.run_here, False)
        vm.is_running = lambda: False
        vm.ensure()
        self.assertEquals(open(vm.confdfile, 'r').read(), """\
# configure-kvm: do not edit this file directly. It will be overwritten!
VMMEM="512"
VMCORES="1"
VMRG="test"
VMDISK="10"
TAPID="1000"
VNC_PORT="1000"
MONITOR_PORT="21000"
NETWORKS="SRV"
MACSRV="foo"
""")
        self.assertEquals(os.readlink(vm.initfile), 'kvm')

        self.assertEquals(len(self.subpcall.mock_calls), 0)
        self.assertEquals(len(self.call.mock_calls), 0)
